DBMap utils
MystenLabs/mysten-infra pull request #103
Opened 2022-07-30 06:18 UTC by oxade

Reduces boilerplate code for opening DBMaps and dumping.
Added derive macro to derive handy utils.

2022-07-31 19:17 UTC, patrickkuo requested changes

2022-07-31 19:17 UTC, patrickkuo commented on crates/typed-store-macros-tests/Cargo.toml
> +[package]
Why put the test in a different crate?

2022-07-31 19:17 UTC, patrickkuo commented on crates/typed-store-macros/src/lib.rs
> +        // }
commented out code

2022-07-31 19:17 UTC, patrickkuo commented on crates/typed-store-macros/src/lib.rs
> +        use pre::pre;
should avoid generating `use` in proc macro, very likely to cause reimport error when expanded

2022-07-31 19:17 UTC, patrickkuo commented on crates/typed-store-macros/src/lib.rs
> +        const DB_DEFAULT_CF_NAME: &str = "default";
This might cause problem as well if this macro is used more then once in the same file

2022-07-31 19:17 UTC, patrickkuo commented on crates/typed-store-macros/src/lib.rs
> +            fn adjusted_db_options(
looks like this function don't really need to be in the macro? Can it live in the trait instead?

2022-07-31 19:17 UTC, patrickkuo commented on crates/typed-store-macros/src/lib.rs
> +            fn list_tables(path: PathBuf) -> anyhow::Result<Vec<String>> {
ditto

2022-07-31 19:17 UTC, patrickkuo commented on crates/typed-store-macros/src/lib.rs
> +    let info = input.fields.iter().map(|f| {
will be more readable if we extract this to `fn extract_info` ?

2022-08-01 00:58 UTC, oxade commented on crates/typed-store-macros-tests/Cargo.toml
> +[package]
I tried to put them in same crate but kept getting this error
`error: can't use a procedural macro from the same crate that defines it`
The solution from my research was to separate it out

2022-08-01 12:01 UTC, patrickkuo approved these changes
LGTM

2022-08-01 12:01 UTC, merged