Replace boilerplate serialization
MystenLabs/mysten-infra pull request #33
Opened 2022-03-09 01:41 UTC by oxade

@huitseeker 
Can you provide a descriptive comment for the method.
Also we probably need a better name for it.

2022-03-09 12:18 UTC, asonnino approved these changes
LGTM

If I want to use the function `skip_prior_to` of the store with a key of type `(TransactionDigest, SequenceNumber)`, is there a way to tell the store to "sort" those keys by sequence number rather than a weird mix of TransactionDigest and SequenceNumber?

2022-03-09 14:51 UTC, huitseeker requested changes
Thanks, this is much cleaner.
The `#[inline(always)]` will hit compilation times (which are already not super) hard, and the ThinLTO can inline most cases already so I think we should get rid of the always. I left a few other remarks.

2022-03-09 14:51 UTC, huitseeker commented on typed-store/src/rocks/mod.rs
> +#[inline(always)]
Please replace with `#[inline]`, the always is not the best idea here, even though it sounds like it should:
http://troubles.md/rust-optimization/#dont-use-inline-always

2022-03-09 14:51 UTC, huitseeker commented on typed-store/src/rocks/mod.rs
> +pub fn be_fix_int_ser<S>(t: &S) -> Result<Vec<u8>, TypedStoreError>
How about `serialize_big_endian`, or something more evocative?

2022-03-09 14:51 UTC, huitseeker commented on typed-store/src/rocks/mod.rs
> +/// TODO: Good description of why we're doing this
The doc on the default Rocks comparator being BE is a bit obscure, and you'd have to look into rust-rocksdb for how this is selected every time, but we can certainly mention in a sentence that "rocksdb stores keys in BE and has a seek operator on iterators": 
https://github.com/facebook/rocksdb/wiki/Iterator#introduction

2022-03-14 00:41 UTC, huitseeker approved these changes

2022-03-14 00:41 UTC, merged