add opening as secondary
MystenLabs/mysten-infra pull request #67
Opened 2022-05-04 03:34 UTC by oxade

2022-05-04 12:02 UTC, huitseeker commented
What's the use case for this?

2022-05-05 16:58 UTC, huitseeker requested changes
1. If you want to expose the secondary opening, I think you must expose a variant of [`try_catch_up_with_the_primary`](https://docs.rs/rocksdb/0.15.0/rocksdb/struct.DB.html#method.try_catch_up_with_primary).

2. I'd like to see a test on this:
- open a DB as primary, write one key/value to it,
- open the same DB as secondary with a side path, read the value
- for extra points, have the primary write to the same key twice, and observe the update after `try_catch_up_with_primary`

Requesting changes for at least the separator bug.

2022-05-05 16:58 UTC, huitseeker commented on typed-store/src/rocks/mod.rs
> +    secondary_path.push("/SECONDARY");
I'm OK with the notion of a suffix, but Is there a chance we may clobber another (e.g. existing) secondary path?
You can use this `Into<Option>` technique to add an optional secondary path argument:
https://vidify.org/blog/rust-parameters/#b-with-intooptiont

2022-05-05 16:58 UTC, huitseeker commented on typed-store/src/rocks/mod.rs
> +    secondary_path.push("/SECONDARY");
No need to add the separator when using `PathBuf::push`: this breaks on non-unixes.
https://doc.rust-lang.org/std/path/struct.PathBuf.html#method.push

2022-05-23 04:37 UTC, oxade commented
Not needed any longer

2022-05-23 04:37 UTC, closed without merging